name: release

on:
  push:
    branches:
    tags:
      - 'v*'
  pull_request:

jobs:
  release:
    strategy:
      matrix:
        go-version: [1.19.x]
        os: [ubuntu-latest]

    name: Release for (${{ matrix.os}}, Go ${{ matrix.go-version }})
    permissions:
      contents: write
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - uses: actions/setup-go@v3
        with:
          go-version: ${{ matrix.go-version }}
          cache: true
      - shell: bash
        run: echo "sha_short=$(git rev-parse --short HEAD)" >> $GITHUB_ENV
      - id: cache
        uses: actions/cache@v3
        with:
          path: dist/${{ matrix.os }}
          key: ${{ matrix.go }}-${{ env.sha_short }}
      - name: Build all packages
        run: go build -v ./...
      - name: Run GoReleaser
        uses: goreleaser/goreleaser-action@v3
        if: success() && startsWith(github.ref, 'refs/tags/') && steps.cache.outputs.cache-hit != 'true'
        with:
          version: latest
          args: release --clean
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
